src/config/routes.rb
Rails.application.routes.draw do

  resources :owneds
  resources :rents
  resources :roles
  resources :movies do
    resources :reviews
  end

  devise_for :users

  resources :admin

  scope 'admin', module: 'admin', as: 'admin' do
    devise_for :users
    resources :movies
    resources :roles

    ## Liste de donnée
    get 'list/users', to: 'list#users_list' # Liste Utilisateur
    get 'list/movies', to: 'list#movies_list' # Liste Film
    get 'list/roles', to: 'list#roles_list' # Liste Roles
    # Liste Commentaire
    # Liste Location
    # Liste Like
    # Liste Ajout
    # Liste possède + disponibilité

    ## Dashboard
    get 'dashboard/index', to: 'dashboard#dashboard'
  end

  resources :library
  root 'movies#index'

  get 'home/private'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'browse' => 'browse#browse', as: :browse
end

src/app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

src/app/controllers/rents_controller.rb
class RentsController < ApplicationController
  before_action :set_rent, only: [:show, :edit, :update, :destroy]
  # GET /rents/1
  # GET /rents/1.json
  def index
    @rents = Rent.all
  end
  # GET /rents/1
  # GET /rents/1.json
  def show
  end

  # GET /rents/new
  def new
    @rent = Rent.new
  end

  # GET /rents/1/edit
  def edit
  end

  # POST /rents
  # POST /rents.json
  def create
    @rent = Rent.new
    @rent.movie_id = params[:movie_id]
    @rent.user_id = current_user.id
    @rent.date_from = Date.today
    @rent.date_to = Date.today + 30

    puts "ornage"

    respond_to do |format|
      if @rent.save
        format.html { redirect_to request.env['HTTP_REFERER'], notice: 'Rent was successfully added.' }
      else
        format.html { redirect_to request.env['HTTP_REFERER'], notice: 'Rent was not added.' }
      end
    end
  end

  # PATCH/PUT /rents/1
  # PATCH/PUT /rents/1.json
  def update
    respond_to do |format|
      if @rent.update(rent_params)
        format.html { redirect_to @rent, notice: 'Rent was successfully updated.' }
        format.json { render :show, status: :ok, location: @rent }
      else
        format.html { render :edit }
        format.json { render json: @rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rents/1
  # DELETE /rents/1.json
  def destroy
    @rent.destroy
    respond_to do |format|
      format.html { redirect_to rents_url, notice: 'Rent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rent
      @rent = Rent.find(params[:id])
    end
end

src/app/helpers/rents_helper.rb
module RentsHelper
end

src/app/views/rents/_form.html.erb
<%= simple_form_for(@rent) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.association :movie, selected: params[:movie] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

src/app/views/rents/edit.html.erb
<h1>Editing Rent</h1>

<%= render 'form', rent: @rent %>

<%= link_to 'Show', @rent %> |
<%= link_to 'Back', rents_path %>

src/app/views/rents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rents</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Movie</th>
      <th>Date from</th>
      <th>Date to</th>
      <th>Status</th>
      <th>Seen</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <%= Date.today +  30 %>

  <tbody>
    <% @rents.each do |rent| %>
      <tr>
        <td><%= rent.user.username %></td>
        <td><%= rent.movie.name %></td>
        <td><%= rent.date_from %></td>
        <td><%= rent.date_to %></td>
        <td><%= rent.status %></td>
        <td><%= rent.seen %></td>
        <td><%= link_to 'Show', rent %></td>
        <td><%= link_to 'Edit', edit_rent_path(rent) %></td>
        <td><%= link_to 'Destroy', rent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rent', new_rent_path %>

src/app/views/rents/new.html.erb
<h1>New Rent</h1>
<%= render 'form', rent: @rent %>

<%= link_to 'Back', rents_path %>

src/app/views/rents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @rent.user_id %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @rent.movie_id %>
</p>

<p>
  <strong>Date from:</strong>
  <%= @rent.date_from %>
</p>

<p>
  <strong>Date to:</strong>
  <%= @rent.date_to %>
</p>

<p>
  <strong>Status:</strong>
  <%= @rent.status %>
</p>

<p>
  <strong>Seen:</strong>
  <%= @rent.seen %>
</p>

<%= link_to 'Edit', edit_rent_path(@rent) %> |
<%= link_to 'Back', rents_path %>