src/config/routes.rb
Rails.application.routes.draw do

  resources :owneds
  resources :rents
  resources :roles
  resources :movies do
    resources :reviews
  end

  devise_for :users

  resources :admin

  scope 'admin', module: 'admin', as: 'admin' do
    devise_for :users
    resources :movies
    resources :roles

    ## Liste de donnée
    get 'list/users', to: 'list#users_list' # Liste Utilisateur
    get 'list/movies', to: 'list#movies_list' # Liste Film
    get 'list/roles', to: 'list#roles_list' # Liste Roles
    # Liste Commentaire
    # Liste Location
    # Liste Like
    # Liste Ajout
    # Liste possède + disponibilité

    ## Dashboard
    get 'dashboard/index', to: 'dashboard#dashboard'
  end

  resources :library
  root 'movies#index'

  get 'home/private'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'browse' => 'browse#browse', as: :browse
end

src/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    # # création d'un alias
    alias_action :create,:show,:update,:destroy, to: :crud
    # # Utilisation de l'alias avec l'access à repository
    # can [:crud, :repository], Movie, {user_id: :user.id}
    # # L'inverse de can, refus d'acces
    # cannot? [:crud, :repository], Movie, {user_id: :user.id}

    # Pour donner accès au lecture aux utilisateurs connecté
    can [:read], Movie

    if user.id && user.role.name === "member"
      can [:crud], Movie, {user_id: user.id}
      cannot :manage, Admin
    end


    if user.id && user.role.name === "admin"
      can :manage, Movie
      can :manage, Role
      can :manage, Admin
    end

    # can [:create,:show, :update], Movie, {user_id: :user.id}
    # can :manage, Movie, {user_id: user.id}

    # Pour restreindre l'acces si il ya un role admin par exemple
    # if user.admin?
    #  can [:crud], :all # ou [Movie,Post,...]
    # end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/category.rb
class Category < ApplicationRecord
    has_many :movies
end

src/app/models/library.rb
class Library < ApplicationRecord
    belongs_to :movie
    belongs_to :user
end

src/app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :libraries
  has_many :added_movies, through: :libraries, source: :user
  has_many :reviews

  has_one_attached :image
end

src/app/models/owned.rb
class Owned < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

src/app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

src/app/models/review.rb
class Review < ApplicationRecord
    belongs_to :movie
    belongs_to :user
end

src/app/models/role.rb
class Role < ApplicationRecord
end

src/app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login

  has_many :movies

  has_many :libraries
  has_many :library_additions, through: :libraries, source: :movie 

  has_many :reviews

  belongs_to :role

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :username, presence: true, uniqueness: {case_sensitive: false}, format: {with: /\A[a-zA-Z0-9]*\z/}

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many_attached :images       

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_hash).where("lower(username) = :value OR lower(email) = :value", value: login.downcase).first
    else
      where(conditions.to_hash).first
    end
  end

end

src/app/controllers/admin/list_controller.rb
class Admin::ListController < ApplicationController
  layout 'admin'

  def users_list
    authorize! :manage, Admin
    @users = User.all
  end

  def movies_list
    authorize! :manage, Admin
    @movies = Movie.all
  end
  def roles_list
    authorize! :manage, Admin
    @roles = Role.all
  end
end

src/app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!, only: [:private]

  def index
  end

  def private
  end
end

src/app/helpers/admin_helper.rb
module AdminHelper
end

src/app/helpers/application_helper.rb
module ApplicationHelper

    def admin?
        user_signed_in? && current_user.admin?
    end
end

src/app/helpers/home_helper.rb
module HomeHelper
end

src/app/helpers/movies_helper.rb
module MoviesHelper

    def user_add_to_library? user, movie 
        user.libraries.where(user: user, movie: movie).any?
    end
end

src/app/helpers/owneds_helper.rb
module OwnedsHelper
end

src/app/helpers/rents_helper.rb
module RentsHelper
end

src/app/helpers/reviens_helper.rb
module ReviensHelper
end

src/app/helpers/reviews_helper.rb
module ReviewsHelper
end

src/app/helpers/roles_helper.rb
module RolesHelper
end

src/app/views/admin/list/movies_list.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<div class="btn" style="color:black; border-radius: 0"><%= link_to 'New Movie', new_admin_movie_path %></div>

<div class="row">
  <div id="admin" class="col s12">
    <div class="card material-table">
      <table>
        <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Image</th>
          <th>Category</th>
          <th>User</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @movies.each do |movie| %>
          <tr>
            <td><%= movie.name %></td>
            <td><%= movie.description %></td>
            <td><%= image_tag movie.image, class: 'image', style: 'width: 300px; height:300px'%></td>
            <td><%= movie.category %></td>
            <td><%= movie.user_id %></td>
            <td><%= link_to 'Show', movie %></td>
            <td><%= link_to 'Edit', edit_admin_movie_path(movie) %></td>
            <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

src/app/views/admin/list/roles_list.html.erb
<p id="notice"><%= notice %></p>

<h1>Roles</h1>

<div class="btn" style="color:black; border-radius: 0"><%= link_to 'New Role', new_admin_role_path %></div>

<div class="row">
  <div id="admin" class="col s12">
    <div class="card material-table">
      <table>
        <thead>
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @roles.each do |role| %>
          <tr>
            <td><%= role.id %></td>
            <td><%= role.name %></td>
            <td><%= link_to 'Show', role %></td>
            <td><%= link_to 'Edit', edit_admin_role_path(role) %></td>
            <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

src/app/views/admin/list/users_list.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<div class="btn" style="color:black; border-radius: 0"><%= link_to 'New User', new_admin_user_registration_path %></div>

<div class="row">
  <div id="admin" class="col s12">
    <div class="card material-table">
      <table id="datatable">
        <thead>
        <tr>
          <th>Id</th>
          <th>Email</th>
          <th>Username</th>
          <th>Role</th>
          <th colspan="3"></th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.email %></td>
            <td><%= user.username %></td>
            <td><%= user.role.name %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>