src/config/routes.rb
Rails.application.routes.draw do

  resources :owneds
  resources :rents
  resources :roles
  resources :movies do
    resources :reviews
  end

  devise_for :users

  resources :admin

  scope 'admin', module: 'admin', as: 'admin' do
    devise_for :users
    resources :movies
    resources :roles

    ## Liste de donnée
    get 'list/users', to: 'list#users_list' # Liste Utilisateur
    get 'list/movies', to: 'list#movies_list' # Liste Film
    get 'list/roles', to: 'list#roles_list' # Liste Roles
    # Liste Commentaire
    # Liste Location
    # Liste Like
    # Liste Ajout
    # Liste possède + disponibilité

    ## Dashboard
    get 'dashboard/index', to: 'dashboard#dashboard'
  end

  resources :library
  root 'movies#index'

  get 'home/private'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'browse' => 'browse#browse', as: :browse
end

src/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    # # création d'un alias
    alias_action :create,:show,:update,:destroy, to: :crud
    # # Utilisation de l'alias avec l'access à repository
    # can [:crud, :repository], Movie, {user_id: :user.id}
    # # L'inverse de can, refus d'acces
    # cannot? [:crud, :repository], Movie, {user_id: :user.id}

    # Pour donner accès au lecture aux utilisateurs connecté
    can [:read], Movie

    if user.id && user.role.name === "member"
      can [:crud], Movie, {user_id: user.id}
      cannot :manage, Admin
    end


    if user.id && user.role.name === "admin"
      can :manage, Movie
      can :manage, Role
      can :manage, Admin
    end

    # can [:create,:show, :update], Movie, {user_id: :user.id}
    # can :manage, Movie, {user_id: user.id}

    # Pour restreindre l'acces si il ya un role admin par exemple
    # if user.admin?
    #  can [:crud], :all # ou [Movie,Post,...]
    # end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/category.rb
class Category < ApplicationRecord
    has_many :movies
end

src/app/models/library.rb
class Library < ApplicationRecord
    belongs_to :movie
    belongs_to :user
end

src/app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :libraries
  has_many :added_movies, through: :libraries, source: :user
  has_many :reviews

  has_one_attached :image
end

src/app/models/owned.rb
class Owned < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

src/app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

src/app/models/review.rb
class Review < ApplicationRecord
    belongs_to :movie
    belongs_to :user
end

src/app/models/role.rb
class Role < ApplicationRecord
end

src/app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login

  has_many :movies

  has_many :libraries
  has_many :library_additions, through: :libraries, source: :movie 

  has_many :reviews

  belongs_to :role

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :username, presence: true, uniqueness: {case_sensitive: false}, format: {with: /\A[a-zA-Z0-9]*\z/}

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many_attached :images       

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_hash).where("lower(username) = :value OR lower(email) = :value", value: login.downcase).first
    else
      where(conditions.to_hash).first
    end
  end

end

src/app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!, only: [:private]

  def index
  end

  def private
  end
end

src/app/helpers/admin_helper.rb
module AdminHelper
end

src/app/helpers/application_helper.rb
module ApplicationHelper

    def admin?
        user_signed_in? && current_user.admin?
    end
end

src/app/helpers/home_helper.rb
module HomeHelper
end

src/app/helpers/movies_helper.rb
module MoviesHelper

    def user_add_to_library? user, movie 
        user.libraries.where(user: user, movie: movie).any?
    end
end

src/app/helpers/owneds_helper.rb
module OwnedsHelper
end

src/app/helpers/rents_helper.rb
module RentsHelper
end

src/app/helpers/reviens_helper.rb
module ReviensHelper
end

src/app/helpers/reviews_helper.rb
module ReviewsHelper
end

src/app/helpers/roles_helper.rb
module RolesHelper
end

src/app/views/admin/index.html.erb
<div id="page-content-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1>Admin Page</h1>
        <p>Welcome to admin Page</p>
      </div>
    </div>
  </div>
</div>

src/app/views/layouts/_nav.html.erb
<nav class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal"><%= link_to 'ACST Ciné', movies_path %></h5>

    <% if user_signed_in? %>
        <div class="navbar-item" >
            <%= link_to "library", library_index_path, class: "mr-5" %>
        </div>
        <%= link_to 'New Movie', new_movie_path, class: "mr-2" %>

        <%= link_to "sign out", destroy_user_session_path, method: :delete, class: "btn btn-secondary mr-2" %>
    <% else %>
        <%= link_to "sign in", new_user_session_path, class: "btn btn-secondary mr-2" %>
        <%= link_to "sign up", new_user_registration_path, class: "btn btn-outline-primary" %>
    <% end %>
  </nav>

src/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'admin', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% unless flash.empty? %>
      <script type="text/javascript">
          <% flash.each do |f| %>
          <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
          toastr['<%= type %>']('<%= f[1] %>');
          <% end %>
      </script>
    <% end %>
    <div id="wrapper">
      <%= render 'layouts/admin/navbar' %>
      <%= render 'layouts/admin/sidebar' %>
      <%= yield %>
    </div>

  </body>

  <script>
      $("#menu-toggle").on('click',function(e) {
          e.preventDefault();
          $("#wrapper").toggleClass("toggled");
      });
  </script>
</html>

src/app/views/layouts/admin/_sidebar.html.erb
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">
      <a href="#">
        ACST
      </a>
    </li>
    <li>
      <%= link_to 'Dashboard', admin_dashboard_index_path %>
    </li>
    <li>
      <%= link_to 'Users', admin_list_users_path %>
    </li>
    <li>
      <%= link_to 'Movies',admin_list_movies_path %>
    </li>
    <li>
      <%= link_to 'Roles',admin_list_roles_path %>
    </li>
  </ul>
</div>
<a href="#menu-toggle" class="btn btn-default" id="menu-toggle" style="color: white; background-color: black; border-radius: 0">Menu</a>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/nav" %>
  <div class="container" >
    <% unless flash.empty? %>
      <script type="text/javascript">
          <% flash.each do |f| %>
          <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
          toastr['<%= type %>']('<%= f[1] %>');
          <% end %>
      </script>
    <% end %>
    </div>



    <p class="notice"><%= notice %> </p>
    <p class="alert"><%= alert %> </p>

    <%= yield %>

  </body>
</html>